// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

/* ============================================================================
   Tool Exclusion Config Builder — client
   Model: every tool is Exposed or Hidden. A manual's `default_disabled` flag
   only changes how that decision serializes (exclude_tools vs include_tools).
   ========================================================================== */

import { buildConfig as serializeConfig } from "./serialize.js";

const $ = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => [...root.querySelectorAll(sel)];

const esc = (s) =>
  String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

/* ----------------------------------------------------------------- State -- */

let manifest = null;
const manualByName = new Map();
const toolIndex = new Map(); // canonical name -> { tool, manual }
const decisions = new Map(); // manual name -> { defaultDisabled, hidden:Set<canonical> }

const ui = {
  query: "",
  regex: false,
  caseSensitive: false,
  filters: { manuals: new Set(), types: new Set(), decision: "all" },
  sortField: "name",
  sortDir: "asc",
  orderMode: "config", // config | alpha | custom
  manualOrder: null, // array of manual names when custom
  selected: new Set(),
  collapsed: new Set(),
  regexError: false
};

let draggedManual = null;

let storageKey = null;
let saveTimer = null;

function cssEscape(s) {
  return window.CSS && CSS.escape ? CSS.escape(s) : String(s).replace(/["\\]/g, "\\$&");
}

/* -------------------------------------------------------------- Bootstrap -- */

async function boot() {
  manifest = window.__MANIFEST__;
  if (!manifest) {
    try {
      manifest = await (await fetch("/api/manifest")).json();
    } catch {
      manifest = null;
    }
  }

  const root = $("#tools");
  if (!manifest || !Array.isArray(manifest.manuals) || manifest.manuals.length === 0) {
    root.innerHTML = emptyState(
      "No config loaded",
      "Start the builder with <code>npm run config-builder -- &lt;path-to-.utcp_config.json&gt;</code> so it can register your manuals and discover tools."
    );
    $("#sourcePath").textContent = "no manifest";
    return;
  }

  $("#sourcePath").textContent = manifest.source || "—";
  $("#source").title = manifest.source || "";

  for (const manual of manifest.manuals) {
    manualByName.set(manual.name, manual);
    for (const tool of manual.tools) toolIndex.set(tool.name, { tool, manual });
    decisions.set(manual.name, {
      defaultDisabled: manual.defaultDisabled === true,
      removed: false,
      hidden: new Set(manual.tools.filter((t) => t.initiallyHidden).map((t) => t.name))
    });
  }

  storageKey = "utcp-cb:" + signature();
  const restored = loadPersisted();

  try {
    const w = localStorage.getItem("utcp-cb:previewW");
    if (w) document.documentElement.style.setProperty("--preview-w", w);
  } catch {
    /* ignore */
  }

  buildFilterPopover();
  buildGlobalPopover();
  wireEvents();
  $("#sortField").value = ui.sortField;
  $("#manualOrder").value = ui.orderMode;
  measureSticky();
  render();

  if (restored) toast("Restored your previous session", "pos");
}

function signature() {
  // Keyed by config PATH + shape: two different config files with identical
  // manuals must not share (and silently bleed) a persisted session.
  return (
    "v2:" +
    (String(manifest.source || "") + "|" + manifest.manuals.map((m) => `${m.name}#${m.tools.length}`).join("|"))
      .split("")
      .reduce((h, c) => ((h << 5) - h + c.charCodeAt(0)) | 0, 0)
  );
}

/* ------------------------------------------------------------ Persistence -- */

function persist() {
  if (!storageKey) return;
  clearTimeout(saveTimer);
  saveTimer = setTimeout(() => {
    const data = {
      decisions: [...decisions].map(([n, d]) => [n, { defaultDisabled: d.defaultDisabled, removed: d.removed, hidden: [...d.hidden] }]),
      collapsed: [...ui.collapsed],
      orderMode: ui.orderMode,
      manualOrder: ui.manualOrder
    };
    try {
      localStorage.setItem(storageKey, JSON.stringify(data));
    } catch {
      /* storage unavailable; non-fatal */
    }
  }, 250);
}

function loadPersisted() {
  if (!storageKey) return false;
  let data;
  try {
    data = JSON.parse(localStorage.getItem(storageKey) || "null");
  } catch {
    return false;
  }
  if (!data || !Array.isArray(data.decisions)) return false;
  for (const [name, d] of data.decisions) {
    const dec = decisions.get(name);
    if (!dec) continue;
    dec.defaultDisabled = d.defaultDisabled === true;
    dec.removed = d.removed === true;
    const validNames = new Set(manualByName.get(name).tools.map((t) => t.name));
    dec.hidden = new Set((d.hidden || []).filter((n) => validNames.has(n)));
  }
  ui.collapsed = new Set((data.collapsed || []).filter((n) => manualByName.has(n)));
  if (data.orderMode === "alpha" || data.orderMode === "custom") ui.orderMode = data.orderMode;
  if (Array.isArray(data.manualOrder)) ui.manualOrder = data.manualOrder.filter((n) => manualByName.has(n));
  return true;
}

/* ------------------------------------------------------------- Search/sort */

function buildMatcher() {
  ui.regexError = false;
  const q = ui.query.trim();
  if (!q) return () => true;

  if (ui.regex) {
    let re;
    try {
      re = new RegExp(q, ui.caseSensitive ? "" : "i");
    } catch {
      ui.regexError = true;
      return null;
    }
    return (tool, mn) =>
      re.test(tool.name) || re.test(tool.shortName) || re.test(tool.description) || re.test(mn) || tool.tags.some((t) => re.test(t));
  }

  const needle = ui.caseSensitive ? q : q.toLowerCase();
  const norm = (s) => (ui.caseSensitive ? s : s.toLowerCase());
  return (tool, mn) =>
    norm(tool.name).includes(needle) ||
    norm(tool.shortName).includes(needle) ||
    norm(tool.description).includes(needle) ||
    norm(mn).includes(needle) ||
    tool.tags.some((t) => norm(t).includes(needle));
}

function isHidden(mn, tn) {
  return decisions.get(mn).hidden.has(tn);
}
function toolState(mn, tn) {
  return isHidden(mn, tn) ? "hidden" : "exposed";
}

function passesDecisionFilter(manual, tool) {
  const d = ui.filters.decision;
  if (d === "all") return true;
  const hidden = isHidden(manual.name, tool.name);
  if (d === "exposed") return !hidden;
  if (d === "hidden") return hidden;
  if (d === "changed") return hidden !== tool.initiallyHidden;
  return true;
}

function sortTools(tools, mn) {
  const dir = ui.sortDir === "asc" ? 1 : -1;
  return tools.slice().sort((a, b) => {
    let r = 0;
    if (ui.sortField === "state") r = Number(isHidden(mn, a.name)) - Number(isHidden(mn, b.name));
    else if (ui.sortField === "desc") r = a.description.length - b.description.length;
    else r = a.shortName.localeCompare(b.shortName);
    return (r || a.shortName.localeCompare(b.shortName)) * dir;
  });
}

function orderedManuals() {
  const list = manifest.manuals.slice();
  if (ui.orderMode === "alpha") {
    list.sort((a, b) => a.name.localeCompare(b.name));
  } else if (ui.orderMode === "custom" && Array.isArray(ui.manualOrder)) {
    const idx = new Map(ui.manualOrder.map((n, i) => [n, i]));
    const at = (n) => (idx.has(n) ? idx.get(n) : Number.MAX_SAFE_INTEGER);
    list.sort((a, b) => at(a.name) - at(b.name));
  }
  return list;
}

function computeView() {
  const matcher = buildMatcher();
  const toolFiltersActive = ui.query.trim() !== "" || ui.filters.decision !== "all";

  const manuals = orderedManuals();
  const view = [];
  for (const manual of manuals) {
    if (ui.filters.manuals.size && !ui.filters.manuals.has(manual.name)) continue;
    if (ui.filters.types.size && !ui.filters.types.has(manual.type)) continue;

    let tools = manual.tools.filter((t) => passesDecisionFilter(manual, t));
    tools = matcher ? tools.filter((t) => matcher(t, manual.name)) : [];
    tools = sortTools(tools, manual.name);

    if (toolFiltersActive && tools.length === 0) continue;
    view.push({ manual, tools });
  }
  return view;
}

/* -------------------------------------------------------------- Selection -- */

function syncSelectionUi() {
  $("#selCount").textContent = String(ui.selected.size);
  $("#bulkbar").hidden = ui.selected.size === 0;
}

function bulkSetHidden(hidden) {
  for (const name of ui.selected) {
    const entry = toolIndex.get(name);
    if (entry) setToolHidden(entry.manual.name, name, hidden);
  }
  render();
  persist();
}

function selectAllMatches() {
  // Skip removed manuals — their rows are display:none, so selecting them
  // would silently include invisible tools in bulk Expose/Hide.
  for (const { manual, tools } of computeView()) {
    if (decisions.get(manual.name)?.removed) continue;
    for (const t of tools) ui.selected.add(t.name);
  }
  render();
}

function clearSelection() {
  ui.selected.clear();
  render();
}

/* ----------------------------------------------------------------- Render -- */

function emptyState(title, body) {
  return `<div class="empty"><svg><use href="#i-search"/></svg><h2>${esc(title)}</h2><p>${body}</p></div>`;
}

/* Per-manual discovery diagnostics (structure/registration failures) — badge
   with the first error inline and the full list in the tooltip. */
function manualFailureBadge(manual) {
  const d = manual.diagnostics;
  if (!d || (d.structureValid !== false && d.registered !== false)) return "";
  const label = d.structureValid === false ? "invalid template" : "failed to register";
  const detail = (d.errors || []).join("\n") || label;
  return `<span class="badge badge--fail" title="${esc(detail)}">⚠ ${esc(label)}</span>`;
}

function manualCountsHtml(manual) {
  const hidden = decisions.get(manual.name).hidden.size;
  const exposed = manual.tools.length - hidden;
  return `<span class="pos">${exposed}</span> exposed · <span class="neg">${hidden}</span> hidden · ${manual.tools.length}`;
}

function toolRow(manual, tool) {
  const state = toolState(manual.name, tool.name);
  const selected = ui.selected.has(tool.name);
  const tags = tool.tags.slice(0, 6).map((t) => `<span class="tag">${esc(t)}</span>`).join("");
  const label = state === "exposed" ? "Exposed" : "Hidden";
  const icon = state === "exposed" ? "i-eye" : "i-eye-off";
  return `<div class="tool${selected ? " is-selected" : ""}" data-tool="${esc(tool.name)}" data-manual="${esc(manual.name)}" data-state="${state}">
    <input type="checkbox" class="check tool__select" ${selected ? "checked" : ""} title="Select for bulk Expose / Hide" aria-label="Select ${esc(tool.shortName)}" />
    <button type="button" class="state-toggle" title="Click to ${state === "exposed" ? "hide" : "expose"} this tool" aria-label="Toggle visibility for ${esc(tool.shortName)}, currently ${label}">
      <span class="dot"></span><svg class="ico"><use href="#${icon}"/></svg>${label}
    </button>
    <div class="tool__main">
      <div class="tool__row1">
        <code class="tool__name" title="Canonical name: ${esc(tool.name)}">${esc(tool.shortName)}</code>
        <button type="button" class="tool__copy" data-copy="${esc(tool.name)}" title="Copy canonical name" aria-label="Copy canonical name"><svg class="ico"><use href="#i-copy"/></svg></button>
      </div>
      ${tool.description ? `<p class="tool__desc">${esc(tool.description)}</p>` : ""}
      ${tags ? `<div class="tool__tags">${tags}</div>` : ""}
    </div>
  </div>`;
}

function manualSection(entry) {
  const { manual, tools } = entry;
  const dec = decisions.get(manual.name);
  const collapsed = ui.collapsed.has(manual.name);
  const selN = manual.tools.filter((t) => ui.selected.has(t.name)).length;
  const allSel = selN > 0 && selN === manual.tools.length;
  const someSel = selN > 0 && !allSel;

  const removed = dec.removed;
  const body =
    tools.length === 0
      ? `<p class="manual__empty">No tools discovered for this manual.</p>`
      : tools.map((t) => toolRow(manual, t)).join("");

  return `<section class="manual${collapsed ? " is-collapsed" : ""}${removed ? " is-removed" : ""}" data-manual="${esc(manual.name)}">
    <header class="manual__head">
      <button type="button" class="manual__grip" draggable="true" title="Drag to reorder this manual" aria-label="Drag to reorder ${esc(manual.name)}"><svg class="ico"><use href="#i-grip"/></svg></button>
      <button type="button" class="disclosure" aria-expanded="${!collapsed}" title="Collapse / expand this manual" aria-label="Toggle ${esc(manual.name)}"><svg class="ico"><use href="#i-chevron"/></svg></button>
      <input type="checkbox" class="check manual__select" ${allSel ? "checked" : ""} data-some="${someSel}" title="Select every tool in this manual for bulk actions" aria-label="Select all tools in ${esc(manual.name)}" />
      <h2 class="manual__name" title="${esc(manual.name)}">${esc(manual.name)}</h2>
      <span class="badge" title="Provider type">${esc(manual.type)}</span>
      ${manualFailureBadge(manual)}
      ${removed ? `<span class="removed-pill" title="Excluded from the generated config">removed</span>` : `<span class="manual__counts">${manualCountsHtml(manual)}</span>`}
      <span class="manual__spacer"></span>
      <div class="manual__actions">
        <label class="switch" title="ON: write this manual as an allowlist (default_disabled + include_tools). OFF: write it as a denylist (exclude_tools).">
          <input type="checkbox" class="manual__dd" ${dec.defaultDisabled ? "checked" : ""} />
          <span class="switch__track"></span>
          <code>default_disabled</code>
        </label>
        <button type="button" class="mini-btn mini-btn--pos" data-act="expose-all" title="Expose every tool in this manual"><svg class="ico"><use href="#i-eye"/></svg>Expose all</button>
        <button type="button" class="mini-btn mini-btn--neg" data-act="hide-all" title="Hide every tool in this manual"><svg class="ico"><use href="#i-eye-off"/></svg>Hide all</button>
        <button type="button" class="mini-btn mini-btn--icon manual__remove" aria-pressed="${removed}" title="${removed ? "Restore this manual to the generated config" : "Remove this manual entirely from the generated config"}" aria-label="Toggle removal of ${esc(manual.name)}"><svg class="ico"><use href="#i-trash"/></svg></button>
      </div>
    </header>
    <div class="manual__body">${body}</div>
  </section>`;
}

function render() {
  const root = $("#tools");
  const view = computeView();
  $("#searchField").classList.toggle("is-invalid", ui.regexError);

  if (view.length === 0) {
    root.innerHTML = ui.regexError
      ? emptyState("Invalid regular expression", `<code>${esc(ui.query)}</code> isn’t valid regex. Fix it or turn off the <code>.*</code> toggle.`)
      : emptyState("No tools match", "Adjust your search or filters to see tools.");
  } else {
    root.innerHTML = view.map(manualSection).join("");
    for (const el of $$(".manual__select")) if (el.dataset.some === "true") el.indeterminate = true;
  }

  updateStatus(view);
  updatePreview();
  syncSelectionUi();
  measureSticky();
}

function tallyDecisions() {
  let hidden = 0;
  let dd = 0;
  let removed = 0;
  let activeTools = 0;
  for (const [name, d] of decisions) {
    if (d.removed) {
      removed += 1;
      continue;
    }
    hidden += d.hidden.size;
    activeTools += manualByName.get(name).tools.length;
    if (d.defaultDisabled) dd += 1;
  }
  return { hidden, dd, removed, exposed: activeTools - hidden };
}

function updateStatus(view) {
  const totalTools = manifest.manuals.reduce((n, m) => n + m.tools.length, 0);
  const shown = view.reduce((n, e) => n + e.tools.length, 0);
  const { hidden, dd, removed, exposed } = tallyDecisions();
  $("#matchStatus").innerHTML =
    `<b>${shown}</b> / ${totalTools} tools shown · <b>${exposed}</b> exposed, <b>${hidden}</b> hidden · ${dd} default_disabled` +
    (removed ? ` · <b>${removed}</b> manual${removed === 1 ? "" : "s"} removed` : "");
}

function patchManual(mn) {
  const section = $(`.manual[data-manual="${cssEscape(mn)}"]`);
  const counts = section && $(".manual__counts", section); // absent when the manual is removed
  if (counts) counts.innerHTML = manualCountsHtml(manualByName.get(mn));
}

/* ----------------------------------------------------------------- Mutate -- */

function setToolHidden(mn, tn, hidden) {
  const set = decisions.get(mn).hidden;
  if (hidden) set.add(tn);
  else set.delete(tn);
}

function toggleTool(mn, tn) {
  setToolHidden(mn, tn, !isHidden(mn, tn));
  const row = $(`.tool[data-tool="${cssEscape(tn)}"]`);
  if (row) {
    const state = toolState(mn, tn);
    row.dataset.state = state;
    const label = state === "exposed" ? "Exposed" : "Hidden";
    const btn = $(".state-toggle", row);
    btn.innerHTML = `<span class="dot"></span><svg class="ico"><use href="#${state === "exposed" ? "i-eye" : "i-eye-off"}"/></svg>${label}`;
    // Keep tooltip + accessible name in sync with the new state.
    btn.title = `Click to ${state === "exposed" ? "hide" : "expose"} this tool`;
    const short = toolIndex.get(tn)?.tool.shortName ?? tn;
    btn.setAttribute("aria-label", `Toggle visibility for ${short}, currently ${label}`);
  }
  patchManual(mn);
  if (ui.filters.decision !== "all" || ui.sortField === "state") render();
  else {
    updateStatus(computeView());
    updatePreview();
  }
  persist();
}

function manualSetAll(mn, hidden) {
  const set = decisions.get(mn).hidden;
  set.clear();
  if (hidden) for (const t of manualByName.get(mn).tools) set.add(t.name);
  render();
  persist();
}

function setManualDefaultDisabled(mn, value) {
  decisions.get(mn).defaultDisabled = value;
  updatePreview();
  persist();
}

function globalExpose(hidden) {
  for (const [name, d] of decisions) {
    d.hidden.clear();
    if (hidden) for (const t of manualByName.get(name).tools) d.hidden.add(t.name);
  }
}
function globalDefaultDisabled(value) {
  for (const [, d] of decisions) d.defaultDisabled = value;
}
function resetDecisions() {
  for (const manual of manifest.manuals) {
    const dec = decisions.get(manual.name);
    dec.defaultDisabled = manual.defaultDisabled === true;
    dec.removed = false;
    dec.hidden = new Set(manual.tools.filter((t) => t.initiallyHidden).map((t) => t.name));
  }
  ui.selected.clear();
  ui.orderMode = "config";
  ui.manualOrder = null;
  $("#manualOrder").value = "config";
}

/* ----------------------------------------------------------------- Output -- */

function buildConfig() {
  // Emit in the current display order; serialize.js drops removed manuals.
  return serializeConfig(manifest.config || {}, orderedManuals(), decisions);
}

function syntaxHighlight(json) {
  // Match tokens on the RAW JSON, then HTML-escape each token's text. (Escaping
  // first would turn every `"` into `&quot;`, so the string/key regex below would
  // never match — leaving keys/strings uncolored and producing no .j-key spans
  // for the preview-scroll feature to target.) Structural gaps ({}[],: + space)
  // contain no HTML-special chars, so they're safe to pass through unescaped.
  return String(json).replace(
    /("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false)\b|\bnull\b|-?\d+(?:\.\d*)?(?:[eE][+-]?\d+)?)/g,
    (m) => {
      let cls = "j-num";
      if (/^"/.test(m)) cls = /:$/.test(m) ? "j-key" : "j-str";
      else if (/true|false/.test(m)) cls = "j-bool";
      else if (/null/.test(m)) cls = "j-null";
      return `<span class="${cls}">${esc(m)}</span>`;
    }
  );
}

function updatePreview() {
  const cfg = buildConfig();
  $("#jsonOut").innerHTML = syntaxHighlight(JSON.stringify(cfg, null, 2));
  const { hidden, dd, removed } = tallyDecisions();
  // Count what actually serializes (discovered-only manuals have no template
  // and are never emitted), not the on-screen manual count.
  const emitted = Array.isArray(cfg.manual_call_templates) ? cfg.manual_call_templates.length : 0;
  $("#previewMeta").textContent =
    `${emitted} manuals · ${hidden} hidden · ${dd} default_disabled` + (removed ? ` · ${removed} removed` : "");
}

/* Smooth-scroll the JSON preview to a manual's config block + briefly flash it.
   Triggered by clicking/expanding a manual (NOT by dragging to reorder). */
function scrollPreviewToManual(name) {
  const out = $("#jsonOut");
  const scroller = out?.closest(".preview__code");
  if (!scroller) return;

  // On narrow layouts the preview is an off-canvas drawer — make sure it's
  // open. On wide layouts the column is already visible; do NOT set the class
  // there, or the drawer pops open unrequested when the window later narrows.
  const narrow = window.matchMedia("(max-width: 1079px)").matches;
  if (narrow && !document.body.classList.contains("preview-open")) {
    document.body.classList.add("preview-open");
    $("#previewToggle")?.setAttribute("aria-expanded", "true");
  }

  requestAnimationFrame(() => {
    // The mcpServers entry key (e.g. `"proxyman-mcp":`) sits near the top of this
    // manual's serialized block; fall back to the template's name string value.
    const keyText = `"${name}":`;
    const nameVal = `"${name}"`;
    const target =
      $$(".j-key", out).find((el) => el.textContent === keyText) ||
      $$(".j-str", out).find((el) => el.textContent === nameVal);
    if (!target) return;

    // Delta-based offset (transform-invariant, so it works mid drawer-slide).
    const sRect = scroller.getBoundingClientRect();
    const tRect = target.getBoundingClientRect();
    const top = scroller.scrollTop + (tRect.top - sRect.top) - scroller.clientHeight / 2 + tRect.height / 2;
    scroller.scrollTo({ top: Math.max(0, top), behavior: "smooth" });

    target.classList.remove("j-flash");
    void target.offsetWidth; // restart the flash animation
    target.classList.add("j-flash");
  });
}

function currentJson() {
  return JSON.stringify(buildConfig(), null, 2) + "\n";
}

function safeFilename() {
  const raw = $("#filename").value.trim() || "custom.utcp_config.json";
  const base = raw.replace(/[^A-Za-z0-9._-]/g, "_").replace(/^\.+/, "") || "custom.utcp_config.json";
  return base.endsWith(".json") ? base : base + ".json";
}

function download() {
  const blob = new Blob([currentJson()], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = safeFilename();
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  toast(`Downloaded ${a.download}`, "pos");
}

async function copyJson() {
  try {
    await navigator.clipboard.writeText(currentJson());
    toast("Config copied to clipboard", "pos");
  } catch {
    toast("Copy failed — clipboard blocked", "neg");
  }
}

async function saveToDisk(overwrite = false) {
  try {
    const res = await fetch("/api/save", {
      method: "POST",
      headers: { "content-type": "application/json", "x-config-builder-token": manifest.token || "" },
      body: JSON.stringify({ filename: safeFilename(), config: buildConfig(), overwrite: overwrite === true })
    });
    const data = await res.json();
    if (res.ok && data.ok) {
      toast(`Saved to ${data.path}`, "pos");
    } else if (res.status === 409 && data.exists) {
      if (window.confirm(`${safeFilename()} already exists in ./configs/ — overwrite it?`)) {
        await saveToDisk(true);
      }
    } else {
      toast(data.error || "Save failed", "neg");
    }
  } catch {
    toast("Save needs the local server (npm run config-builder)", "neg");
  }
}

/* ------------------------------------------------------------------ Toasts */

function toast(message, kind = "") {
  const el = document.createElement("div");
  el.className = "toast" + (kind ? ` toast--${kind}` : "");
  el.innerHTML = `<svg class="ico"><use href="#${kind === "neg" ? "i-info" : "i-check"}"/></svg><span>${esc(message)}</span>`;
  $("#toasts").appendChild(el);
  setTimeout(() => {
    el.style.transition = "opacity .25s, transform .25s";
    el.style.opacity = "0";
    el.style.transform = "translateY(8px)";
    setTimeout(() => el.remove(), 280);
  }, 2600);
}

/* ---------------------------------------------------------------- Popovers */

function buildFilterPopover() {
  const types = [...new Set(manifest.manuals.map((m) => m.type))].sort();
  const decisionOpts = [
    ["all", "All tools"],
    ["exposed", "Exposed only"],
    ["hidden", "Hidden only"],
    ["changed", "Changed from default"]
  ];
  const pop = $("#filterPop");
  pop.innerHTML = `
    <div class="pop-group">
      <div class="pop-label">Decision</div>
      ${decisionOpts.map(([v, l]) => `<label class="pop-row"><input type="radio" name="dec" value="${v}" ${v === "all" ? "checked" : ""}/> ${l}</label>`).join("")}
    </div>
    <div class="pop-group">
      <div class="pop-label">Provider type</div>
      ${types.map((t) => `<label class="pop-row"><input type="checkbox" class="f-type" value="${esc(t)}"/> ${esc(t)}</label>`).join("")}
    </div>
    <div class="pop-group">
      <div class="pop-label">Manual</div>
      <div style="max-height:200px;overflow:auto">
      ${manifest.manuals.map((m) => `<label class="pop-row"><input type="checkbox" class="f-manual" value="${esc(m.name)}"/> <code>${esc(m.name)}</code></label>`).join("")}
      </div>
    </div>`;

  pop.addEventListener("change", () => {
    ui.filters.decision = $('input[name="dec"]:checked', pop).value;
    ui.filters.types = new Set($$(".f-type:checked", pop).map((el) => el.value));
    ui.filters.manuals = new Set($$(".f-manual:checked", pop).map((el) => el.value));
    const count = (ui.filters.decision !== "all" ? 1 : 0) + (ui.filters.types.size ? 1 : 0) + (ui.filters.manuals.size ? 1 : 0);
    const badge = $("#filterCount");
    badge.hidden = count === 0;
    badge.textContent = String(count);
    render();
  });
}

function buildGlobalPopover() {
  const pop = $("#globalPop");
  const actions = [
    ["expose-all", "Expose every tool", "remove all hides everywhere"],
    ["hide-all", "Hide every tool", "deny everything across all manuals"],
    ["dd-on", "Set default_disabled on all", "serialize every manual as an allowlist"],
    ["dd-off", "Clear default_disabled on all", "serialize every manual as a denylist"],
    ["preset-deny", "Preset · deny all", "default_disabled off + hide all"],
    ["preset-allow", "Preset · allowlist all", "default_disabled on + expose all"]
  ];
  pop.innerHTML = actions
    .map(([act, label, sub]) => `<button type="button" class="pop-action" data-global="${act}"><svg class="ico"><use href="#i-bolt"/></svg><span>${label}<br><small>${sub}</small></span></button>`)
    .join("");

  pop.addEventListener("click", (e) => {
    const btn = e.target.closest("[data-global]");
    if (!btn) return;
    const act = btn.dataset.global;
    if (act === "expose-all") globalExpose(false);
    else if (act === "hide-all") globalExpose(true);
    else if (act === "dd-on") globalDefaultDisabled(true);
    else if (act === "dd-off") globalDefaultDisabled(false);
    else if (act === "preset-deny") (globalDefaultDisabled(false), globalExpose(true));
    else if (act === "preset-allow") (globalDefaultDisabled(true), globalExpose(false));
    closePopovers();
    render();
    persist();
    toast("Applied: " + btn.querySelector("span").childNodes[0].textContent.trim(), "pos");
  });
}

function togglePopover(hostBtn, pop) {
  const open = pop.hidden === false;
  closePopovers();
  if (!open) {
    pop.hidden = false;
    hostBtn.setAttribute("aria-expanded", "true");
  }
}
function closePopovers() {
  for (const pop of $$(".popover")) pop.hidden = true;
  for (const b of [$("#filterBtn"), $("#globalBtn")]) b.setAttribute("aria-expanded", "false");
}

/* ------------------------------------------------------------------ Events */

function wireEvents() {
  $("#tools").addEventListener("click", (e) => {
    const disclosure = e.target.closest(".disclosure");
    if (disclosure) {
      const sec = disclosure.closest(".manual");
      const name = sec.dataset.manual;
      if (ui.collapsed.has(name)) ui.collapsed.delete(name);
      else ui.collapsed.add(name);
      sec.classList.toggle("is-collapsed");
      disclosure.setAttribute("aria-expanded", String(!ui.collapsed.has(name)));
      if (!ui.collapsed.has(name)) scrollPreviewToManual(name); // expanded → reveal in preview
      persist();
      return;
    }
    const toggle = e.target.closest(".state-toggle");
    if (toggle) {
      const row = toggle.closest(".tool");
      toggleTool(row.dataset.manual, row.dataset.tool);
      return;
    }
    const copy = e.target.closest(".tool__copy");
    if (copy) {
      navigator.clipboard?.writeText(copy.dataset.copy).then(() => toast("Copied " + copy.dataset.copy), () => toast("Copy failed", "neg"));
      return;
    }
    const removeBtn = e.target.closest(".manual__remove");
    if (removeBtn) {
      const name = removeBtn.closest(".manual").dataset.manual;
      const dec = decisions.get(name);
      dec.removed = !dec.removed;
      render();
      persist();
      toast(dec.removed ? `Removed “${name}” from the config` : `Restored “${name}”`, dec.removed ? "neg" : "pos");
      return;
    }
    const act = e.target.closest("[data-act]");
    if (act) {
      manualSetAll(act.closest(".manual").dataset.manual, act.dataset.act === "hide-all");
      return;
    }

    // Plain click on a manual header (its name/badge/counts/empty space) — not a
    // control and not the drag grip — scrolls the JSON preview to that server.
    const head = e.target.closest(".manual__head");
    if (head && !e.target.closest("button, input, label, .switch, .manual__grip")) {
      scrollPreviewToManual(head.closest(".manual").dataset.manual);
    }
  });

  wireDragReorder();
  wireResizer();

  $("#tools").addEventListener("change", (e) => {
    if (e.target.classList.contains("tool__select")) {
      const row = e.target.closest(".tool");
      if (e.target.checked) ui.selected.add(row.dataset.tool);
      else ui.selected.delete(row.dataset.tool);
      row.classList.toggle("is-selected", e.target.checked);
      syncSelectionUi();
      const head = row.closest(".manual");
      const manual = manualByName.get(head.dataset.manual);
      const selN = manual.tools.filter((t) => ui.selected.has(t.name)).length;
      const box = $(".manual__select", head);
      box.checked = selN > 0 && selN === manual.tools.length;
      box.indeterminate = selN > 0 && selN < manual.tools.length;
      return;
    }
    if (e.target.classList.contains("manual__select")) {
      const manual = manualByName.get(e.target.closest(".manual").dataset.manual);
      const want = e.target.checked;
      for (const t of manual.tools) {
        if (want) ui.selected.add(t.name);
        else ui.selected.delete(t.name);
      }
      render();
      return;
    }
    if (e.target.classList.contains("manual__dd")) {
      setManualDefaultDisabled(e.target.closest(".manual").dataset.manual, e.target.checked);
    }
  });

  let searchTimer = null;
  $("#search").addEventListener("input", (e) => {
    ui.query = e.target.value;
    $("#searchClear").hidden = ui.query === "";
    clearTimeout(searchTimer);
    searchTimer = setTimeout(render, 110);
  });
  $("#searchClear").addEventListener("click", () => {
    ui.query = "";
    $("#search").value = "";
    $("#searchClear").hidden = true;
    render();
    $("#search").focus();
  });
  $("#regexToggle").addEventListener("click", (e) => {
    ui.regex = !ui.regex;
    e.currentTarget.setAttribute("aria-pressed", String(ui.regex));
    render();
  });
  $("#caseToggle").addEventListener("click", (e) => {
    ui.caseSensitive = !ui.caseSensitive;
    e.currentTarget.setAttribute("aria-pressed", String(ui.caseSensitive));
    render();
  });

  $("#sortField").addEventListener("change", (e) => {
    ui.sortField = e.target.value;
    render();
  });
  $("#manualOrder").addEventListener("change", (e) => {
    ui.orderMode = e.target.value;
    render();
    persist();
  });
  $("#sortDir").addEventListener("click", (e) => {
    ui.sortDir = ui.sortDir === "asc" ? "desc" : "asc";
    e.currentTarget.dataset.dir = ui.sortDir;
    e.currentTarget.textContent = ui.sortDir === "asc" ? "↑" : "↓";
    e.currentTarget.title = ui.sortDir === "asc" ? "Ascending" : "Descending";
    render();
  });

  $("#filterBtn").addEventListener("click", () => togglePopover($("#filterBtn"), $("#filterPop")));
  $("#globalBtn").addEventListener("click", () => togglePopover($("#globalBtn"), $("#globalPop")));
  document.addEventListener("click", (e) => {
    if (!e.target.closest(".popover-host")) closePopovers();
  });

  $("#downloadBtn").addEventListener("click", download);
  $("#copyBtn").addEventListener("click", copyJson);
  $("#saveBtn").addEventListener("click", () => saveToDisk());
  $("#resetBtn").addEventListener("click", () => {
    resetDecisions();
    render();
    persist();
    toast("Reset to config defaults");
  });
  $("#source").addEventListener("click", () => navigator.clipboard?.writeText(manifest.source || "").then(() => toast("Source path copied")));

  $("#previewToggle").addEventListener("click", () => {
    const open = document.body.classList.toggle("preview-open");
    $("#previewToggle").setAttribute("aria-expanded", String(open));
  });
  $("#previewClose").addEventListener("click", () => {
    document.body.classList.remove("preview-open");
    $("#previewToggle").setAttribute("aria-expanded", "false");
  });

  $("#bulkExpose").addEventListener("click", () => bulkSetHidden(false));
  $("#bulkHide").addEventListener("click", () => bulkSetHidden(true));
  $("#bulkSelectAll").addEventListener("click", selectAllMatches);
  $("#bulkClear").addEventListener("click", clearSelection);

  document.addEventListener("keydown", (e) => {
    // The Host Import panel owns the keyboard while it's open (its own Escape
    // handler closes it) — don't also clear search/selection underneath it.
    if (document.body.classList.contains("view-host")) return;
    const inField = /^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName || "");
    if (e.key === "/" && !inField) {
      e.preventDefault();
      $("#search").focus();
      $("#search").select();
    } else if (e.key === "Escape") {
      if (!$("#filterPop").hidden || !$("#globalPop").hidden) closePopovers();
      else if (document.body.classList.contains("preview-open")) document.body.classList.remove("preview-open");
      else if (ui.query) {
        ui.query = "";
        $("#search").value = "";
        $("#searchClear").hidden = true;
        render();
      } else if (ui.selected.size) clearSelection();
    }
  });

  window.addEventListener("resize", measureSticky, { passive: true });
}

function measureSticky() {
  const topbar = $(".topbar").offsetHeight;
  const toolbar = $(".toolbar").offsetHeight;
  document.documentElement.style.setProperty("--topbar-h", topbar + "px");
  document.documentElement.style.setProperty("--sticky-offset", topbar + toolbar + "px");
}

/* ----------------------------------------------------------- Drag reorder */

function currentOrderNames() {
  return orderedManuals().map((m) => m.name);
}

function clearDragMarks() {
  for (const el of $$(".manual.is-dragging, .manual.drag-over-before, .manual.drag-over-after")) {
    el.classList.remove("is-dragging", "drag-over-before", "drag-over-after");
  }
}

function wireDragReorder() {
  const root = $("#tools");
  root.addEventListener("dragstart", (e) => {
    // Only the grip is draggable (a draggable <button> reliably fires dragstart;
    // making the whole section draggable + a button grip did not).
    const grip = e.target.closest(".manual__grip");
    if (!grip) return;
    const section = grip.closest(".manual");
    if (!section) return;
    draggedManual = section.dataset.manual;
    section.classList.add("is-dragging");
    e.dataTransfer.effectAllowed = "move";
    try {
      e.dataTransfer.setData("text/plain", draggedManual);
      e.dataTransfer.setDragImage(section, 16, 16); // ghost the whole row, not just the grip
    } catch {
      /* some browsers require this in a try */
    }
  });
  root.addEventListener("dragover", (e) => {
    if (!draggedManual) return;
    e.preventDefault();
    e.dataTransfer.dropEffect = "move";
    for (const el of $$(".manual.drag-over-before, .manual.drag-over-after")) {
      el.classList.remove("drag-over-before", "drag-over-after");
    }
    const section = e.target.closest(".manual");
    if (!section || section.dataset.manual === draggedManual) return;
    const rect = section.getBoundingClientRect();
    section.classList.add(e.clientY > rect.top + rect.height / 2 ? "drag-over-after" : "drag-over-before");
  });
  root.addEventListener("drop", (e) => {
    if (!draggedManual) return;
    e.preventDefault();
    const section = e.target.closest(".manual");
    if (section && section.dataset.manual !== draggedManual) {
      const targetName = section.dataset.manual;
      const rect = section.getBoundingClientRect();
      const after = e.clientY > rect.top + rect.height / 2;
      const order = currentOrderNames().filter((n) => n !== draggedManual);
      let idx = order.indexOf(targetName);
      if (after) idx += 1;
      order.splice(idx, 0, draggedManual);
      ui.manualOrder = order;
      ui.orderMode = "custom";
      $("#manualOrder").value = "custom";
      persist();
    }
    clearDragMarks();
    draggedManual = null;
    render();
  });
  root.addEventListener("dragend", () => {
    clearDragMarks();
    draggedManual = null;
  });
}

/* --------------------------------------------------------- Preview resize */

function wireResizer() {
  const resizer = $("#resizer");
  if (!resizer) return;
  resizer.addEventListener("pointerdown", (e) => {
    e.preventDefault();
    resizer.setPointerCapture(e.pointerId);
    resizer.classList.add("is-dragging");
    document.body.classList.add("is-resizing");
    const onMove = (ev) => {
      const w = Math.min(Math.max(window.innerWidth - ev.clientX, 320), Math.round(window.innerWidth * 0.72));
      document.documentElement.style.setProperty("--preview-w", w + "px");
    };
    const onUp = () => {
      resizer.classList.remove("is-dragging");
      document.body.classList.remove("is-resizing");
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
      try {
        localStorage.setItem("utcp-cb:previewW", document.documentElement.style.getPropertyValue("--preview-w"));
      } catch {
        /* ignore */
      }
    };
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);
  });
  resizer.addEventListener("dblclick", () => {
    document.documentElement.style.removeProperty("--preview-w");
    try {
      localStorage.removeItem("utcp-cb:previewW");
    } catch {
      /* ignore */
    }
  });
}

boot();
