// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

/**
 * Pure config serialization for the Tool Exclusion Config Builder.
 *
 * No DOM dependencies — imported by app.js (in the browser) AND by the Node
 * test suite. Turns the per-manual exposure decisions into a UTCP config:
 *   - default_disabled === true  -> allowlist (include_tools = exposed tools)
 *   - default_disabled === false -> denylist  (exclude_tools = hidden tools)
 *   - removed === true           -> the manual is dropped from the output
 * Manuals are emitted in the order given (so display order == output order).
 */

export const EXCLUSION_KEYS = ["exclude_tools", "include_tools", "default_disabled"];

export function stripExclusionKeys(template) {
  const clone = { ...template };
  for (const key of EXCLUSION_KEYS) delete clone[key];
  return clone;
}

/**
 * @param base            the original parsed config object
 * @param orderedManuals  array of { name, tools: [{ name }] } in display order
 * @param decisions       Map<manualName, { defaultDisabled, removed, hidden:Set<toolName> }>
 */
export function buildConfig(base, orderedManuals, decisions) {
  const safeBase = base && typeof base === "object" ? base : {};
  const templates = Array.isArray(safeBase.manual_call_templates) ? safeBase.manual_call_templates : [];

  const tplByName = new Map();
  for (const t of templates) {
    const n = t && typeof t.name === "string" ? t.name : undefined;
    if (n !== undefined && !tplByName.has(n)) tplByName.set(n, t);
  }

  const out = [];
  for (const manual of orderedManuals) {
    const template = tplByName.get(manual.name);
    if (!template) continue; // discovered-only manual without a source template
    const dec = decisions.get(manual.name);
    if (dec && dec.removed) continue; // excluded from output entirely

    const clean = stripExclusionKeys(template);
    if (!dec) {
      out.push(clean);
      continue;
    }
    const hiddenNames = manual.tools.filter((t) => dec.hidden.has(t.name)).map((t) => t.name).sort();
    const exposedNames = manual.tools.filter((t) => !dec.hidden.has(t.name)).map((t) => t.name).sort();

    if (dec.defaultDisabled) out.push({ ...clean, default_disabled: true, include_tools: exposedNames });
    else if (hiddenNames.length) out.push({ ...clean, exclude_tools: hiddenNames });
    else out.push(clean);
  }

  return { ...safeBase, manual_call_templates: out };
}
