// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

export interface ToolExclusionRule {
  defaultDisabled: boolean;
  exclude: string[];
  include: string[];
}

export type ToolExclusionRegistry = Map<string, ToolExclusionRule>;

const EXCLUSION_KEYS = ["exclude_tools", "include_tools", "default_disabled"] as const;

function toStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.filter((item): item is string => typeof item === "string");
}

export function parseExclusionRule(
  template: Record<string, unknown> | null | undefined
): ToolExclusionRule | null {
  if (!template || typeof template !== "object") {
    return null;
  }
  const hasExclusionKey = EXCLUSION_KEYS.some((key) => key in template);
  if (!hasExclusionKey) {
    return null;
  }
  return {
    defaultDisabled: template.default_disabled === true,
    exclude: toStringArray(template.exclude_tools),
    include: toStringArray(template.include_tools)
  };
}

export function stripExclusionKeys(
  template: Record<string, unknown>
): Record<string, unknown> {
  const clone: Record<string, unknown> = { ...template };
  for (const key of EXCLUSION_KEYS) {
    delete clone[key];
  }
  return clone;
}

export function getManualNameFromToolName(toolName: string): string {
  const dotIndex = toolName.indexOf(".");
  return dotIndex === -1 ? toolName : toolName.slice(0, dotIndex);
}

/**
 * Mirror the UTCP SDK's manual-name → identifier sanitization. Discovered/exposed
 * tool names are prefixed with this sanitized form (e.g. a manual named
 * "proxyman-mcp" appears as "proxyman_mcp.<tool>"), but exclusion rules are keyed
 * by the raw config template name. Registering under both keys lets the runtime
 * matcher find the rule regardless of which form the tool name carries.
 */
function sanitizeManualName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^[0-9]/, "_$&");
}

export function getToolShortName(toolName: string, manualName: string): string {
  const prefix = `${manualName}.`;
  return toolName.startsWith(prefix) ? toolName.slice(prefix.length) : toolName;
}

export function isToolExcluded(
  toolName: string,
  accessName: string,
  registry: ToolExclusionRegistry
): boolean {
  const manualName = getManualNameFromToolName(toolName);
  const rule = registry.get(manualName);
  if (!rule) {
    return false;
  }

  const shortName = getToolShortName(toolName, manualName);
  const bareName = toolName.slice(toolName.lastIndexOf(".") + 1);
  const aliasName = manualName === toolName ? toolName : `${manualName}.${bareName}`;
  const candidates = new Set([toolName, shortName, bareName, aliasName, accessName]);
  const listed = (names: string[]): boolean => names.some((name) => candidates.has(name));

  if (rule.defaultDisabled) {
    return !listed(rule.include);
  }
  return listed(rule.exclude);
}

export function applyManualExclusion(
  registry: ToolExclusionRegistry,
  template: Record<string, unknown>
): Record<string, unknown> {
  const name = typeof template?.name === "string" ? template.name : undefined;
  const rule = parseExclusionRule(template);
  if (name) {
    const sanitized = sanitizeManualName(name);
    if (rule) {
      registry.set(name, rule);
      if (sanitized !== name) {
        registry.set(sanitized, rule);
      }
    } else {
      registry.delete(name);
      registry.delete(sanitized);
    }
  }
  return stripExclusionKeys(template);
}

export function buildExclusionRegistryFromConfig(
  rawConfig: Record<string, unknown>
): { registry: ToolExclusionRegistry; sanitizedConfig: Record<string, unknown> } {
  const registry: ToolExclusionRegistry = new Map();
  const templates = rawConfig?.manual_call_templates;
  if (!Array.isArray(templates)) {
    return { registry, sanitizedConfig: rawConfig };
  }
  const sanitizedTemplates = templates.map((template) =>
    template && typeof template === "object"
      ? applyManualExclusion(registry, template as Record<string, unknown>)
      : template
  );
  return {
    registry,
    sanitizedConfig: { ...rawConfig, manual_call_templates: sanitizedTemplates }
  };
}
